export const PERMISSIONS = {
  // =========================================================
  // USERS
  // =========================================================
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  GET_PROFIL: "GET_PROFIL",
  GET_ALL_PROFILS: "GET_ALL_PROFILS",

  SEARCH_USER: "SEARCH_USER",
  FILTER_USERS_BY_ROLE: "FILTER_USERS_BY_ROLE",

  ACTIVATE_ACCOUNT: "ACTIVATE_ACCOUNT",
  DEACTIVATE_ACCOUNT: "DEACTIVATE_ACCOUNT",

  // Aliases UI existants
  GET_ALL_USERS: "GET_ALL_PROFILS",
  GET_USER_INFOS: "GET_PROFIL",

  // =========================================================
  // ROLES
  // =========================================================
  CREATE_ROLE: "CREATE_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",

  GET_ALL_ROLES: "GET_ALL_ROLES",
  GET_ROLE_PERMISSIONS: "GET_ROLE_PERMISSIONS",
  GET_ROLE_NAMES: "GET_ROLE_NAMES",

  // Alias UI existant
  GET_ROLE_INFOS: "GET_ROLE_PERMISSIONS",

  // =========================================================
  // ASSETS / BIENS
  // =========================================================
  CREATE_ASSET: "CREATE_ASSET",
  UPDATE_ASSET: "UPDATE_ASSET",
  DELETE_ASSET: "DELETE_ASSET",

  GET_ASSET: "GET_ASSET",
  GET_ALL_ASSETS: "GET_ALL_ASSETS",
  GET_ASSET_INFOS: "GET_ASSET_INFOS",

  GET_ASSETS_BY_STATUS: "GET_ASSETS_BY_STATUS",
  GET_ASSETS_BY_TYPE: "GET_ASSETS_BY_TYPE",

  SEARCH_ASSET: "SEARCH_ASSET",

  GET_ARCHIVED_ASSETS: "GET_ARCHIVED_ASSETS",
  SEARCH_ARCHIVED_ASSETS: "SEARCH_ARCHIVED_ASSETS",

  DISPOSE_ASSET: "DISPOSE_ASSET",
  RENT_ASSET: "RENT_ASSET",

  // Ancien nom Front.
  // L'affectation actuelle modifie le bien.
  ASSIGN_ASSET: "UPDATE_ASSET",

  // =========================================================
  // STOCK
  // Canonical Backend names
  // =========================================================
  CREATE_ITEM: "CREATE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",

  GET_ITEM: "GET_ITEM",
  GET_ALL_ITEMS: "GET_ALL_ITEMS",

  SEARCH_ITEM: "SEARCH_ITEM",
  GET_ITEM_STAT: "GET_ITEM_STAT",

  CREATE_IN_STOCK: "CREATE_IN_STOCK",
  UPDATE_ITEM_QUANTITY: "UPDATE_ITEM_QUANTITY",

  CREATE_ITEM_REQUEST: "CREATE_ITEM_REQUEST",
  GET_ITEM_REQUEST: "GET_ITEM_REQUEST",
  GET_ALL_ITEM_REQUESTS: "GET_ALL_ITEM_REQUESTS",

  APROUVE_ITEM_REQUEST: "APROUVE_ITEM_REQUEST",
  REJECT_ITEM_REQUEST: "REJECT_ITEM_REQUEST",
  CANCEL_ITEM_REQUEST: "CANCEL_ITEM_REQUEST",
  CONFIRM_ITEM_REQUEST_DELIVERY:
    "CONFIRM_ITEM_REQUEST_DELIVERY",

  FILTER_ITEM_REQUESTS_BY_USER:
    "FILTER_ITEM_REQUESTS_BY_USER",

  GET_ITEMS_WITH_LOW_STOCK:
    "GET_ITEMS_WITH_LOW_STOCK",

  GET_STOCK_MOVEMENT_PER_ITEM:
    "GET_STOCK_MOVEMENT_PER_ITEM",

  GET_LOW_STOCK_ALERTS_BY_PERIOD:
    "GET_LOW_STOCK_ALERTS_BY_PERIOD",

  READ_STOCK_ALERTS:
    "READ_STOCK_ALERTS",

  // ---------------------------------------------------------
  // Legacy Front aliases → Backend réel
  // ---------------------------------------------------------
  CREATE_ARTICLE: "CREATE_ITEM",
  UPDATE_ARTICLE: "UPDATE_ITEM",
  DELETE_ARTICLE: "DELETE_ITEM",
  GET_ALL_ARTICLES: "GET_ALL_ITEMS",

  CREATE_SUPPLY_REQUEST:
    "CREATE_ITEM_REQUEST",

  VALIDATE_SUPPLY_REQUEST:
    "APROUVE_ITEM_REQUEST",

  REJECT_SUPPLY_REQUEST:
    "REJECT_ITEM_REQUEST",

  // IMPORTANT:
  // CREATE_STOCK_ENTRY / CREATE_STOCK_EXIT /
  // GET_STOCK_HISTORY / GET_STOCK_ALERTS
  // ne sont PAS mappés arbitrairement ici.
  // Ils seront reliés à leurs endpoints réels
  // pendant la correction des actions Stock.

  CREATE_STOCK_ENTRY:
    "CREATE_IN_STOCK",

  CREATE_STOCK_EXIT:
    "UPDATE_ITEM_QUANTITY",

  GET_STOCK_HISTORY:
    "GET_STOCK_MOVEMENT_PER_ITEM",

  GET_STOCK_ALERTS:
    "GET_ITEMS_WITH_LOW_STOCK",

  // =========================================================
  // PUBLIC LIGHTING
  // =========================================================
  CREATE_LIGHT_POINT:
    "CREATE_LIGHT_POINT",

  UPDATE_LIGHT_POINT:
    "UPDATE_LIGHT_POINT",

  UPDATE_LIGHT_POINT_STATUS:
    "UPDATE_LIGHT_POINT_STATUS",

  DELETE_LIGHT_POINT:
    "DELETE_LIGHT_POINT",

  GET_LIGHT_POINT:
    "GET_LIGHT_POINT",

  GET_ALL_LIGHT_POINT:
    "GET_ALL_LIGHT_POINT",

  SEARCH_LIGHT_POINTS:
    "SEARCH_LIGHT_POINTS",

  FILTER_LIGHT_POINTS_BY_STATUS:
    "FILTER_LIGHT_POINTS_BY_STATUS",

  REPORT_FAILURE:
    "REPORT_FAILURE",

  GET_FAILURE:
    "GET_FAILURE",

  GET_ALL_FAILURE:
    "GET_ALL_FAILURE",

  SCHEDULE_INTERVENTION:
    "SCHEDULE_INTERVENTION",

  GET_INTERVENTION:
    "GET_INTERVENTION",

  SEARCH_INTERVENTIONS:
    "SEARCH_INTERVENTIONS",

  START_INTERVENTION:
    "START_INTERVENTION",

  COMPLETE_INTERVENTION:
    "COMPLETE_INTERVENTION",

  // Legacy UI aliases
  CREATE_LIGHT:
    "CREATE_LIGHT_POINT",

  UPDATE_LIGHT:
    "UPDATE_LIGHT_POINT",

  DELETE_LIGHT:
    "DELETE_LIGHT_POINT",

  GET_ALL_LIGHTS:
    "GET_ALL_LIGHT_POINT",

  CREATE_INTERVENTION:
    "SCHEDULE_INTERVENTION",

  // هادي مؤقتاً ما غاديش نعتمد عليها
  // حتى نربط action المحدد بالBackend.
  UPDATE_INTERVENTION:
    "START_INTERVENTION",

  // =========================================================
  // DASHBOARD
  // =========================================================
  GET_CONNECTED_USERNAME:
    "GET_CONNECTED_USERNAME",

  GET_ROLE_NAME:
    "GET_ROLE_NAME",

  COUNT_USERS:
    "COUNT_USERS",

  COUNT_ASSET:
    "COUNT_ASSET",

  COUNT_ASSETS:
    "COUNT_ASSETS",

  COUNT_ASSETS_BY_STATUS:
    "COUNT_ASSETS_BY_STATUS",

  COUNT_ITEMS:
    "COUNT_ITEMS",

  COUNT_LIGHT_POINTS:
    "COUNT_LIGHT_POINTS",

  COUNT_LIGHT_POINTS_BY_STATUS:
    "COUNT_LIGHT_POINTS_BY_STATUS",

  COUNT_FAILURES:
    "COUNT_FAILURES",

  COUNT_INTERVENTIONS_BY_STATUS:
    "COUNT_INTERVENTIONS_BY_STATUS",

  COUNT_IN_STOCK_BY_ITEM:
    "COUNT_IN_STOCK_BY_ITEM",

  COUNT_IN_STOCK_BY_PERIOD:
    "COUNT_IN_STOCK_BY_PERIOD",

  COUNT_ITEM_REQUESTS_BY_STATUS:
    "COUNT_ITEM_REQUESTS_BY_STATUS",

  COUNT_LOW_STOCK_ALERTS:
    "COUNT_LOW_STOCK_ALERTS",

  COUNT_STOCK_MOVEMENT_BY_PERIOD:
    "COUNT_STOCK_MOVEMENT_BY_PERIOD",

  COUNT_TOTAL_IN_STOCK:
    "COUNT_TOTAL_IN_STOCK",

  COUNT_TOTAL_QUANTITIES:
    "COUNT_TOTAL_QUANTITIES",

  // =========================================================
  // NOTIFICATIONS
  // =========================================================
  COUNT_NOTIF:
    "COUNT_NOTIF",

  FILTER_NOTIF_BY_STATUS:
    "FILTER_NOTIF_BY_STATUS",

  MARK_NOTIF_AS_READ:
    "MARK_NOTIF_AS_READ",

  MARK_ALL_NOTIF_AS_READ:
    "MARK_ALL_NOTIF_AS_READ",

  GET_ACCIDENT_NOTIFICATION:
    "GET_ACCIDENT_NOTIFICATION",

  GET_DISPOSAL_NOTIFICATION:
    "GET_DISPOSAL_NOTIFICATION",

  GET_FUEL_TANK_NOTIFICATION:
    "GET_FUEL_TANK_NOTIFICATION",

  GET_MAINTENANCE_NOTIFICATION:
    "GET_MAINTENANCE_NOTIFICATION",

  GET_RENTAL_NOTIFICATION:
    "GET_RENTAL_NOTIFICATION",

  GET_FAILURE_NOTIFICATION:
    "GET_FAILURE_NOTIFICATION",

  GET_INTERVENTION_NOTIFICATION:
    "GET_INTERVENTION_NOTIFICATION",

  GET_ALERT_STOCK_MVMT_OFF_DOCS:
    "GET_ALERT_STOCK_MVMT_OFF_DOCS",

  GET_ITEM_REQUEST_NOTIFICATION:
    "GET_ITEM_REQUEST_NOTIFICATION",

  // =========================================================
  // OTHER ASSET OPERATIONS
  // =========================================================
  GET_ACCIDENT:
    "GET_ACCIDENT",

  GET_ALL_ACCIDENT:
    "GET_ALL_ACCIDENT",

  REGISTER_ACCIDENT:
    "REGISTER_ACCIDENT",

  GET_DISPOSAL:
    "GET_DISPOSAL",

  GET_ALL_DISPOSALS:
    "GET_ALL_DISPOSALS",

  GET_FUEL_TANK:
    "GET_FUEL_TANK",

  GET_ALL_FUEL_TANKS:
    "GET_ALL_FUEL_TANKS",

  REFUL_VEHICLE:
    "REFUL_VEHICLE",

  GET_MAINTENANCE:
    "GET_MAINTENANCE",

  GET_ALL_MAINTENANCE:
    "GET_ALL_MAINTENANCE",

  SCHEDULE_MAINTENANCE:
    "SCHEDULE_MAINTENANCE",

  START_MAINTENANCE:
    "START_MAINTENANCE",

  COMPLETE_MAINTENANCE:
    "COMPLETE_MAINTENANCE",

  CANCEL_MAINTENANCE:
    "CANCEL_MAINTENANCE",

  UPDATE_MAINTENANCE:
    "UPDATE_MAINTENANCE",

  UPDATE_MAINTENANCE_STATUS:
    "UPDATE_MAINTENANCE_STATUS",

  DELETE_MAINTENANCE:
    "DELETE_MAINTENANCE",

  GET_RENTAL:
    "GET_RENTAL",

  GET_ALL_RENTALS:
    "GET_ALL_RENTALS",

  UPDATE_RENTAL:
    "UPDATE_RENTAL",

  CANCEL_RENTAL:
    "CANCEL_RENTAL",

  // =========================================================
  // TEMPORARY FRONT-ONLY FEATURES
  //
  // Backend ne possède actuellement aucune authority
  // GENERATE_REPORT / EXPORT_PDF / EXPORT_EXCEL /
  // UPDATE_PROFILE / CHANGE_PASSWORD / MANAGE_SETTINGS.
  //
  // On les garde uniquement pour que le code existant compile.
  // Ils ne doivent PAS être considérés comme permissions Backend.
  // =========================================================
  GENERATE_REPORT:
    "__FRONT_GENERATE_REPORT__",

  EXPORT_PDF:
    "__FRONT_EXPORT_PDF__",

  EXPORT_EXCEL:
    "__FRONT_EXPORT_EXCEL__",

  UPDATE_PROFILE:
    "__FRONT_UPDATE_PROFILE__",

  CHANGE_PASSWORD:
    "__FRONT_CHANGE_PASSWORD__",

  MANAGE_SETTINGS:
    "__FRONT_MANAGE_SETTINGS__",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const NOTIFICATION_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.COUNT_NOTIF,
  PERMISSIONS.FILTER_NOTIF_BY_STATUS,
  PERMISSIONS.MARK_NOTIF_AS_READ,
  PERMISSIONS.MARK_ALL_NOTIF_AS_READ,

  PERMISSIONS.GET_ACCIDENT_NOTIFICATION,
  PERMISSIONS.GET_DISPOSAL_NOTIFICATION,
  PERMISSIONS.GET_FUEL_TANK_NOTIFICATION,
  PERMISSIONS.GET_MAINTENANCE_NOTIFICATION,
  PERMISSIONS.GET_RENTAL_NOTIFICATION,
  PERMISSIONS.GET_FAILURE_NOTIFICATION,
  PERMISSIONS.GET_INTERVENTION_NOTIFICATION,
  PERMISSIONS.GET_ALERT_STOCK_MVMT_OFF_DOCS,
  PERMISSIONS.GET_ITEM_REQUEST_NOTIFICATION,
  PERMISSIONS.READ_STOCK_ALERTS,
];

export const REPORT_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.GET_ALL_PROFILS,
  PERMISSIONS.GET_ALL_ASSETS,
  PERMISSIONS.GET_ALL_ITEMS,
  PERMISSIONS.GET_ALL_LIGHT_POINT,
];
