import 'dart:convert';
import 'dart:typed_data';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import '../models/app_document.dart';
import '../models/lighting.dart';

class LightingApiException implements Exception {
  const LightingApiException(this.statusCode,this.message); final int statusCode; final String message;
  @override String toString()=>message;
}

class LightingApiService {
  static const _baseUrl=String.fromEnvironment('API_BASE_URL',defaultValue:'http://127.0.0.1:8081');
  static const _cookieKey='sgpbse_auth_cookie';

  Future<List<LightPoint>> getLights()=>_list('/sgpbse/lightPoint/all',_light,auth:true);
  Future<List<LightPoint>> getPublicLights()=>_list('/sgpbse/lightPoint/public/all',_light,auth:false);
  Future<List<FailureReport>> getFailures()=>_list('/sgpbse/failure/all',_failure,auth:true);
  Future<List<Intervention>> getInterventions()=>_list('/sgpbse/intervention/all',_intervention,auth:true);
  Future<List<Technician>> getTechnicians()=>_list('/sgpbse/intervention/technicians',_technician,auth:true);

  Future<List<FailureReport>> getPublicOpenFailures() async {
    final response=await _request('GET','/sgpbse/failure/public/open',auth:false);
    final raw=jsonDecode(utf8.decode(response.bodyBytes)); if(raw is! List) throw const LightingApiException(500,'UNEXPECTED_RESPONSE');
    return raw.whereType<Map>().map((x){final j=Map<String,dynamic>.from(x);return FailureReport(id:_int(j['id']),lightId:_int(j['lightPointId']),lightReference:'',lightDesignation:'',lightDesignationAr:'',description:'',reportedBy:'PUBLIC',reportedAt:DateTime.now(),status:_failureStatus(j['status']),documents:[]);}).toList();
  }

  Future<LightPoint> createLight(LightPoint light) async { final r=await _request('POST','/sgpbse/lightPoint/create',auth:true,body:_lightPayload(light)); final id=_int(jsonDecode(utf8.decode(r.bodyBytes))); await _uploadMany('/sgpbse/lightPoint/joinDoc/$id',light.documents,auth:true); return _light(await _object('/sgpbse/lightPoint/$id',auth:true)); }
  Future<LightPoint> updateLight(LightPoint light,List<AppDocument> previous) async { final kept=light.documents.map((d)=>d.backendId).whereType<int>().toSet(); for(final old in previous){final id=old.backendId;if(id!=null&&!kept.contains(id))await _request('DELETE','/sgpbse/lightPoint/${light.id}/document/$id',auth:true);} await _request('PUT','/sgpbse/lightPoint/update/${light.id}',auth:true,body:_lightPayload(light)); await _request('PUT','/sgpbse/lightPoint/updateStatus/${light.id}',auth:true,rawBody:jsonEncode(_backendStatus(light.status))); await _uploadMany('/sgpbse/lightPoint/joinDoc/${light.id}',light.documents,auth:true); return _light(await _object('/sgpbse/lightPoint/${light.id}',auth:true)); }
  Future<void> deleteLight(int id) async { await _request('DELETE','/sgpbse/lightPoint/delete/$id',auth:true); }

  Future<FailureReport> createFailure({required int lightId,required String description,required String reportedBy,required List<AppDocument> documents}) async { final j=await _objectRequest('POST','/sgpbse/failure/report/$lightId',auth:true,body:{'description':description,'lightPointId':lightId,'reportedBy':reportedBy}); final f=_failure(j); await _uploadMany('/sgpbse/failure/joinDoc/${f.id}',documents,auth:true); return f; }
  Future<FailureReport> createPublicFailure({required int lightId,required String description,required List<AppDocument> documents}) async { final j=await _objectRequest('POST','/sgpbse/failure/public/report/$lightId',auth:false,body:{'description':description,'lightPointId':lightId,'reportedBy':'PUBLIC'}); final f=_failure(j); await _uploadMany('/sgpbse/failure/public/joinDoc/${f.id}',documents,auth:false); return f; }

  Future<Intervention> createIntervention({required int failureId,required int technicianId,required DateTime date,required String description,required List<AppDocument> documents}) async { final j=await _objectRequest('POST','/sgpbse/intervention/schedule/$failureId',auth:true,body:{'interventionDate':_dateTime(date),'description':description,'technician_id':technicianId}); final i=_intervention(j); await _uploadMany('/sgpbse/intervention/joinDoc/${i.id}',documents,auth:true); return i; }
  Future<Intervention> completeIntervention({required int id,required String report,required double cost,required DateTime completedAt,required List<AppDocument> photos,required List<AppDocument> documents}) async { final j=await _objectRequest('POST','/sgpbse/intervention/complete/$id',auth:true,body:{'report':report,'cost':cost,'completedAt':_dateTime(completedAt)}); await _uploadMany('/sgpbse/intervention/joinDoc/$id',[...photos,...documents],auth:true); return _intervention(j); }

  Future<Uint8List> downloadDocument(AppDocument d) async { if(d.fileBytes!=null)return d.fileBytes!; final id=d.backendId;if(id==null)throw const LightingApiException(400,'INVALID_DOCUMENT_ID'); return (await _request('GET','/sgpbse/document/$id/content',auth:true)).bodyBytes; }

  Map<String,dynamic> _lightPayload(LightPoint l)=>{'reference':l.reference.trim().toUpperCase(),'designation_fr':l.designation.trim(),'designation_ar':l.designationAr.trim(),'location':l.localisation.trim(),'latitude':l.latitude,'longitude':l.longitude,'installationDate':_date(l.installationDate),'power':l.power};
  LightPoint _light(Map<String,dynamic> j)=>LightPoint(id:_int(j['id']),reference:_text(j['reference']),designation:_text(j['designation_fr']),designationAr:_text(j['designation_ar'],_text(j['designation_fr'])),localisation:_text(j['location']),latitude:_double(j['latitude']),longitude:_double(j['longitude']),status:_lightStatus(j['lightPointStatus']),installationDate:DateTime.tryParse(_text(j['installationDate']))??DateTime.now(),power:_double(j['power']),documents:_documents(j['documents']));
  FailureReport _failure(Map<String,dynamic> j)=>FailureReport(id:_int(j['id']),lightId:_int(j['lightPointId']),lightReference:_text(j['lightReference']),lightDesignation:_text(j['lightDesignation_fr']),lightDesignationAr:_text(j['lightDesignation_ar'],_text(j['lightDesignation_fr'])),description:_text(j['description']),reportedBy:_text(j['reportedBy'],'PUBLIC'),reportedAt:DateTime.tryParse(_text(j['reportDate']))??DateTime.now(),status:_failureStatus(j['workflowStatus']),documents:_documents(j['documents']));
  Intervention _intervention(Map<String,dynamic> j){final docs=_documents(j['documents']);return Intervention(id:_int(j['id']),failureId:_int(j['failureId']),technicianId:_int(j['technicianId']),technicianName:_text(j['technician_name']),technicianNameAr:_text(j['technician_name_ar'],_text(j['technician_name'])),technicianLocalisation:_text(j['technicianLocalisation']),interventionDate:DateTime.tryParse(_text(j['interventionDate']))??DateTime.now(),description:_text(j['description']),completed:_text(j['status'])=='COMPLETED',completedAt:_dt(j['completedAt']),report:_nullable(j['report']),cost:j['cost']==null?null:_double(j['cost']),photos:docs.where((d)=>d.type==DocumentType.photo).toList(),documents:docs.where((d)=>d.type!=DocumentType.photo).toList());}
  Technician _technician(Map<String,dynamic> j)=>Technician(id:_int(j['id']),name:_text(j['name']),nameAr:_text(j['nameAr'],_text(j['name'])),phone:_text(j['phone']),localisation:_text(j['localisation']),latitude:j['latitude']==null?double.nan:_double(j['latitude']),longitude:j['longitude']==null?double.nan:_double(j['longitude']),active:j['active']!=false);

  List<AppDocument> _documents(dynamic raw){if(raw is! List)return[];return raw.whereType<Map>().toList().asMap().entries.map((e){final j=Map<String,dynamic>.from(e.value);final id=_int(j['id'],-(e.key+1));final path=_text(j['path']);final parts=path.replaceAll('\\','/').split('/');final fn=parts.isEmpty||parts.last.isEmpty?'document':parts.last;return AppDocument(id:id,backendId:id>0?id:null,name:_text(j['title_fr'],_text(j['title_ar'],fn)),type:_docType(_text(j['type'],'OTHER')),fileName:fn,uploadDate:DateTime.now(),category:_text(j['documentType'])=='DOCUMENT_OFFICIEL'?DocumentCategory.official:DocumentCategory.attachment);}).toList();}
  Future<List<T>> _list<T>(String path,T Function(Map<String,dynamic>) map,{required bool auth})async{final r=await _request('GET',path,auth:auth);final d=jsonDecode(utf8.decode(r.bodyBytes));if(d is! List)throw const LightingApiException(500,'UNEXPECTED_RESPONSE');return d.whereType<Map>().map((x)=>map(Map<String,dynamic>.from(x))).toList();}
  Future<Map<String,dynamic>> _object(String path,{required bool auth})async=>_decode(await _request('GET',path,auth:auth));
  Future<Map<String,dynamic>> _objectRequest(String method,String path,{required bool auth,Map<String,dynamic>? body})async=>_decode(await _request(method,path,auth:auth,body:body));
  Map<String,dynamic> _decode(http.Response r){final d=jsonDecode(utf8.decode(r.bodyBytes));if(d is! Map)throw const LightingApiException(500,'UNEXPECTED_RESPONSE');return Map<String,dynamic>.from(d);}
  Future<http.Response> _request(String method,String path,{required bool auth,Map<String,dynamic>? body,String? rawBody})async{final req=http.Request(method,Uri.parse('$_baseUrl$path'))..headers.addAll({'Accept':'application/json','Content-Type':'application/json'});if(auth){final c=await _cookie();req.headers['Cookie']=c;}if(body!=null)req.body=jsonEncode(body);if(rawBody!=null)req.body=rawBody;final r=await http.Response.fromStream(await req.send());if(r.statusCode<200||r.statusCode>=300)throw LightingApiException(r.statusCode,_error(r));return r;}
  Future<String> _cookie()async{final v=(await SharedPreferences.getInstance()).getString(_cookieKey);if(v==null||v.trim().isEmpty)throw const LightingApiException(401,'AUTH_REQUIRED');return v;}
  String _error(http.Response r){final b=utf8.decode(r.bodyBytes).trim();if(b.isEmpty)return'SERVER_ERROR';try{final d=jsonDecode(b);if(d is Map){final m=d['message']??d['error'];if(m!=null&&m.toString().trim().isNotEmpty)return m.toString().trim();}}catch(_){}return b.replaceAll('"','').trim();}
  Future<void> _uploadMany(String path,List<AppDocument> docs,{required bool auth})async{for(final d in docs){if(d.fileBytes!=null)await _upload(path,d,auth:auth);}}
  Future<void> _upload(String path,AppDocument d,{required bool auth})async{final bytes=d.fileBytes;if(bytes==null)return;final boundary='----sgpbse-light-${DateTime.now().microsecondsSinceEpoch}';final b=BytesBuilder(copy:false);void w(String s)=>b.add(utf8.encode(s));String safe(String s)=>s.replaceAll('"','_').replaceAll('\r','').replaceAll('\n','');w('--$boundary\r\nContent-Disposition: form-data; name="file"; filename="${safe(d.fileName)}"\r\nContent-Type: application/octet-stream\r\n\r\n');b.add(bytes);w('\r\n');final data=jsonEncode({'title_fr':d.name,'title_ar':d.name,'path':null,'documentType':d.isOfficial?'DOCUMENT_OFFICIEL':'PIECE_JOINTE','type':_docTypeBackend(d.type),'endDate':d.isOfficial&&d.expirationDate!=null?_date(d.expirationDate!):null,'alertThreshold':d.isOfficial?d.reminderDaysBefore??7:null});w('--$boundary\r\nContent-Disposition: form-data; name="data"\r\nContent-Type: application/json; charset=utf-8\r\n\r\n$data\r\n--$boundary--\r\n');final req=http.Request('POST',Uri.parse('$_baseUrl$path'))..headers.addAll({'Accept':'application/json','Content-Type':'multipart/form-data; boundary=$boundary'})..bodyBytes=b.takeBytes();if(auth)req.headers['Cookie']=await _cookie();final r=await http.Response.fromStream(await req.send());if(r.statusCode<200||r.statusCode>=300)throw LightingApiException(r.statusCode,_error(r));}

  int _int(dynamic v,[int f=0])=>v is int?v:int.tryParse(v?.toString()??'')??f; double _double(dynamic v,[double f=0])=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??f; String _text(dynamic v,[String f='']){final s=v?.toString().trim()??'';return s.isEmpty?f:s;} String? _nullable(dynamic v){final s=_text(v);return s.isEmpty?null:s;} DateTime? _dt(dynamic v){final s=_nullable(v);return s==null?null:DateTime.tryParse(s);} String _date(DateTime d)=>'${d.year.toString().padLeft(4,'0')}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';String _dateTime(DateTime d)=>'${_date(d)}T12:00:00';
  LightStatus _lightStatus(dynamic v)=>switch(_text(v)){ 'FAULTY'=>LightStatus.damaged,'MAINTENANCE'=>LightStatus.underMaintenance,'DECOMMISSIONED'=>LightStatus.inactive,_=>LightStatus.active}; String _backendStatus(LightStatus v)=>switch(v){LightStatus.active=>'OPERATIONAL',LightStatus.inactive=>'DECOMMISSIONED',LightStatus.damaged=>'FAULTY',LightStatus.underMaintenance=>'MAINTENANCE'}; FailureStatus _failureStatus(dynamic v)=>switch(_text(v)){ 'RESOLVED'=>FailureStatus.resolved,'IN_PROGRESS'=>FailureStatus.inProgress,_=>FailureStatus.reported};
  DocumentType _docType(String v)=>switch(v){'INVOICE'=>DocumentType.invoice,'RECEIPT'=>DocumentType.receipt,'CONTRACT'=>DocumentType.contract,'REGISTRATION'=>DocumentType.registration,'INSURANCE'=>DocumentType.insurance,'CERTIFICATE'=>DocumentType.certificate,'DELIVERY_NOTE'=>DocumentType.deliveryNote,'EXIT_VOUCHER'=>DocumentType.exitVoucher,'TECHNICAL_SHEET'=>DocumentType.technicalSheet,'WARRANTY'=>DocumentType.warranty,'REPORT'=>DocumentType.report,'PHOTO'=>DocumentType.photo,_=>DocumentType.other}; String _docTypeBackend(DocumentType v)=>switch(v){DocumentType.invoice=>'INVOICE',DocumentType.receipt=>'RECEIPT',DocumentType.contract=>'CONTRACT',DocumentType.registration=>'REGISTRATION',DocumentType.insurance=>'INSURANCE',DocumentType.certificate=>'CERTIFICATE',DocumentType.deliveryNote=>'DELIVERY_NOTE',DocumentType.exitVoucher=>'EXIT_VOUCHER',DocumentType.technicalSheet=>'TECHNICAL_SHEET',DocumentType.warranty=>'WARRANTY',DocumentType.report=>'REPORT',DocumentType.photo=>'PHOTO',DocumentType.other=>'OTHER'};
}
