spring.application.name=SGPBSE

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8081

# Mail configuration
#spring.mail.host=smtp.gmail.com
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}

spring.mail.username=afa46303f4a24e
spring.mail.password=8fabbaa94b23d2

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

