spring.application.name=SGPBSE

# .env
spring.config.import=optional:file:./.env[.properties]

# SERVER
server.port=8081

# DATABASE - POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.orm.jdbc.bind=TRACE

# MAIL - TEST WITH MAILTRAP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# FUTURE GMAIL CONFIGURATION
# Replace the Mailtrap host above with:
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# Keep MAIL_USERNAME and MAIL_PASSWORD in .env